# Generated by Django 5.1.4 on 2026-07-11 14:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('cooperatives', '0002_cooperative_address_cooperative_city_and_more'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Niveau de stock',
                'verbose_name_plural': 'Niveaux de stock',
                'ordering': ['product__sku', 'warehouse__code'],
                'indexes': [models.Index(fields=['cooperative', 'product'], name='inventory_s_coopera_afb9e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('cooperative', 'product', 'warehouse'), name='unique_stock_level_per_product_warehouse'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_level_quantity_never_negative')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('transfer', 'Transfert')], max_length=10)),
                ('reason', models.CharField(choices=[('purchase', 'Achat'), ('sale', 'Vente'), ('adjustment', "Ajustement d'inventaire"), ('transfer', 'Transfert inter-entrepôts'), ('return_customer', 'Retour client'), ('return_supplier', 'Retour fournisseur'), ('loss', 'Perte/casse'), ('initial', 'Stock initial'), ('other', 'Autre')], default='other', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Toujours positive ; le sens est donné par movement_type.', max_digits=14)),
                ('reference', models.CharField(blank=True, help_text='Ex: numéro de bon de réception.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(blank=True, help_text='Renseigné uniquement pour un TRANSFER.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_in', to='warehouses.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Entrepôt source (IN/OUT/ADJUSTMENT) ou entrepôt de départ (TRANSFER).', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_out', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cooperative', 'product', 'warehouse'], name='inventory_s_coopera_9945c0_idx'), models.Index(fields=['cooperative', 'movement_type'], name='inventory_s_coopera_ce9fef_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_positive')],
            },
        ),
    ]
