# Generated by Django 5.1.4 (hand-maintained for roles_permissions)

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0002_cooperative_address_cooperative_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModuleAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('owner', 'Propriétaire / Gérant'), ('admin', 'Administrateur'), ('staff', 'Employé'), ('accountant', 'Comptable')], max_length=20)),
                ('module', models.CharField(max_length=50)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès module par rôle',
                'verbose_name_plural': 'Accès modules par rôle',
                'ordering': ['role', 'module'],
                'indexes': [models.Index(fields=['cooperative', 'is_active'], name='roles_permi_coopera_eed1df_idx')],
                'constraints': [models.UniqueConstraint(fields=('cooperative', 'role', 'module'), name='unique_role_module_per_cooperative')],
            },
        ),
    ]
