# Generated by Django 5.1.4 on 2026-08-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rolemoduleaccess',
            name='roles_permi_coopera_eed1df_idx',
        ),
    ]
