# Generated by Django 5.1.4 on 2026-08-16 22:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0002_remove_rolemoduleaccess_roles_permi_coopera_eed1df_idx'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rolemoduleaccess',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
