# Generated by Django 5.1.4 on 2026-07-09 07:43

import apps.cooperatives.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='default_language',
            field=models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية')], default='fr', max_length=2),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='ice',
            field=models.CharField(blank=True, help_text="Identifiant Commun de l'Entreprise (15 chiffres).", max_length=15, validators=[django.core.validators.RegexValidator(message="L'ICE doit être composé exactement de 15 chiffres.", regex='^\\d{15}$')], verbose_name='ICE'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Raison sociale officielle si différente du nom usuel.', max_length=255),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cooperatives/logos/'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide (9 à 15 chiffres, +indicatif optionnel).', regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='rc_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Registre de Commerce'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='subscription_plan',
            field=models.CharField(choices=[('trial', 'Essai gratuit'), ('basic', 'Basique'), ('pro', 'Pro')], default='trial', max_length=10),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Actif'), ('trial', "En période d'essai"), ('suspended', 'Suspendu'), ('cancelled', 'Résilié')], default='trial', max_length=10),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='trial_ends_at',
            field=models.DateTimeField(default=apps.cooperatives.models.default_trial_end),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
