# Generated by Django 5.1.4 on 2026-08-15 11:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_cooperativeactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='share_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text="Valeur nominale d'une part sociale (MAD).", max_digits=12, verbose_name='Valeur de la part sociale'),
        ),
    ]
