# Generated by Django 5.1.4 on 2026-08-16 21:47

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0004_cooperative_share_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cooperativeactivation',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CooperativeEmailConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='Serveur SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='Port SMTP')),
                ('smtp_username', models.CharField(blank=True, max_length=255, verbose_name='Utilisateur SMTP')),
                ('smtp_password', models.CharField(blank=True, max_length=500, verbose_name='Mot de passe SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('from_name', models.CharField(blank=True, help_text='Nom affiché dans les emails envoyés (ex: Ma Coopérative).', max_length=255, verbose_name="Nom de l'expéditeur")),
                ('from_email', models.EmailField(blank=True, help_text='Adresse email source (ex: noreply@ma-cooperative.com).', max_length=254, verbose_name="Adresse de l'expéditeur")),
                ('is_configured', models.BooleanField(default=False, help_text='Coché pour utiliser cette config SMTP au lieu du serveur global.', verbose_name='Configuration active')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration email',
                'verbose_name_plural': 'Configurations email',
                'indexes': [models.Index(fields=['cooperative'], name='cooperative_coopera_85b99f_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
