# Generated by Django 5.1.4 on 2026-08-16 22:11

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0005_add_cooperative_email_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('invoice_issued', 'Facture émise'), ('payment_received', 'Paiement reçu'), ('contribution_pending', 'Cotisation en attente'), ('overdue_reminder', 'Rappel de retard'), ('invitation', 'Invitation'), ('activation', 'Activation de compte'), ('password_reset', 'Réinitialisation de mot de passe')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du destinataire')),
                ('subject', models.CharField(max_length=500, verbose_name='Objet')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échoué')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification email',
                'verbose_name_plural': 'Notifications email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cooperative', 'status'], name='cooperative_coopera_e6e14a_idx'), models.Index(fields=['cooperative', 'notification_type'], name='cooperative_coopera_630526_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
