# Generated by Django 5.1.4 on 2026-08-15 12:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0004_cooperative_share_value'),
        ('members', '0002_sharetransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('assembly_type', models.CharField(choices=[('ordinary', 'Assemblée générale ordinaire'), ('extraordinary', 'Assemblée générale extraordinaire')], default='ordinary', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('quorum_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text="Quorum requis pour la tenue de l'assemblée (en %).", max_digits=5)),
                ('agenda', models.TextField(blank=True, help_text='Ordre du jour.')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmée'), ('done', 'Tenue'), ('cancelled', 'Annulée')], default='draft', max_length=15)),
                ('minutes_notes', models.TextField(blank=True, help_text='Procès-verbal / compte rendu.')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assemblée',
                'verbose_name_plural': 'Assemblées',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('excused', 'Excusé')], default='present', max_length=10)),
                ('vote', models.CharField(blank=True, choices=[('for', 'Pour'), ('against', 'Contre'), ('abstention', 'Abstention')], default=None, max_length=12, null=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='assemblies.assembly')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_attendances', to='members.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Présence à l'assemblée",
                'verbose_name_plural': 'Présences aux assemblées',
            },
        ),
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['cooperative', 'status'], name='assemblies__coopera_c65f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyattendance',
            index=models.Index(fields=['cooperative', 'assembly'], name='assemblies__coopera_edd490_idx'),
        ),
        migrations.AddConstraint(
            model_name='assemblyattendance',
            constraint=models.UniqueConstraint(fields=('assembly', 'member'), name='unique_attendance_per_assembly_member'),
        ),
    ]
