# Generated by Django 5.1.4 on 2026-07-10 21:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0002_cooperative_address_cooperative_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, editable=False, max_length=20)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('partner_kind', models.CharField(choices=[('individual', 'Personne physique'), ('company', 'Personne morale')], default='individual', max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('ice', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="L'ICE doit être composé exactement de 15 chiffres.", regex='^\\d{15}$')], verbose_name='ICE')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide (9 à 15 chiffres, +indicatif optionnel).', regex='^\\+?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=0, help_text='Délai de paiement en jours (0 = comptant).')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Encours maximum autorisé pour ce client (0 = pas de limite définie).', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['cooperative', 'is_customer'], name='partners_pa_coopera_88ca2e_idx'), models.Index(fields=['cooperative', 'is_supplier'], name='partners_pa_coopera_76e4f5_idx')],
                'constraints': [models.UniqueConstraint(fields=('cooperative', 'code'), name='unique_partner_code_per_cooperative'), models.UniqueConstraint(condition=models.Q(('ice', ''), _negated=True), fields=('cooperative', 'ice'), name='unique_partner_ice_per_cooperative')],
            },
        ),
    ]
