# Generated by Django 5.1.4 on 2026-07-10 21:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0002_cooperative_address_cooperative_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('member_number', models.CharField(db_index=True, editable=False, max_length=20)),
                ('member_type', models.CharField(choices=[('individual', 'Personne physique'), ('entity', 'Personne morale')], default='individual', max_length=15)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('cin', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Format de CIN invalide (ex: AB123456).', regex='^[A-Za-z]{1,2}\\d{1,6}$')], verbose_name='CIN')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide (9 à 15 chiffres, +indicatif optionnel).', regex='^\\+?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('join_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('inactive', 'Inactif (parti)')], default='active', max_length=15)),
                ('shares_count', models.PositiveIntegerField(default=0, help_text='Nombre de parts sociales détenues.')),
                ('notes', models.TextField(blank=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['cooperative', 'status'], name='members_mem_coopera_3a4d8e_idx'), models.Index(fields=['cooperative', 'last_name', 'first_name'], name='members_mem_coopera_99a7d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('cooperative', 'member_number'), name='unique_member_number_per_cooperative'), models.UniqueConstraint(condition=models.Q(('cin', ''), _negated=True), fields=('cooperative', 'cin'), name='unique_cin_per_cooperative')],
            },
        ),
    ]
