# Generated by Django 5.1.4 on 2026-08-15 11:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0004_cooperative_share_value'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('subscription', 'Souscription'), ('redemption', 'Retrait')], default='subscription', max_length=15)),
                ('shares_count', models.PositiveIntegerField(help_text='Nombre de parts concernées par ce mouvement.')),
                ('amount_per_share', models.DecimalField(decimal_places=2, help_text="Valeur nominale d'une part au moment du mouvement (MAD).", max_digits=12)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_transactions', to='members.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de parts sociales',
                'verbose_name_plural': 'Mouvements de parts sociales',
                'indexes': [models.Index(fields=['cooperative', 'member', 'transaction_date'], name='members_sha_coopera_7d8320_idx')],
            },
        ),
    ]
