# Generated by Django 5.1.4 on 2026-08-16 22:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_sharetransaction'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sharetransaction',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
