# Generated by Django 5.1.4 (hand-maintained for documents)

import uuid
import django.db.models.deletion
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0002_cooperative_address_cooperative_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('template_type', models.CharField(choices=[('delivery_note', 'Bon de livraison'), ('purchase_order', 'Bon de commande'), ('receipt', 'Bon de réception')], max_length=30)),
                ('header_text', models.TextField(blank=True, help_text="Texte affiché sous la raison sociale dans l'en-tête.")),
                ('footer_text', models.TextField(blank=True, help_text='Ligne(s) ajoutée(s) dans le pied de page (coordonnées, mentions...).')),
                ('terms_text', models.TextField(blank=True, help_text='Conditions générales / remarques affichées sous le document.')),
                ('accent_color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message="La couleur d'accent doit être un code hexadécimal (#RRGGBB).", regex='^#[0-9a-fA-F]{6}$')], help_text="Couleur d'accent du document (#RRGGBB). Vide = couleur par défaut.")),
                ('show_logo', models.BooleanField(default=True, help_text="Afficher le logo de la coopérative dans l'en-tête.")),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
                'ordering': ['template_type'],
                'indexes': [models.Index(fields=['cooperative', 'is_active'], name='documents_tmpl_coop_idx')],
                'constraints': [models.UniqueConstraint(fields=('cooperative', 'template_type'), name='unique_template_type_per_cooperative')],
            },
        ),
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('delivery_note', 'Bon de livraison'), ('purchase_order', 'Bon de commande'), ('receipt', 'Bon de réception')], max_length=30)),
                ('source_type', models.CharField(choices=[('sales_order', 'Commande de vente'), ('purchase_order', "Commande d'achat")], max_length=30)),
                ('source_id', models.UUIDField(db_index=True, editable=False)),
                ('source_number', models.CharField(db_index=True, editable=False, max_length=50)),
                ('pdf_file', models.FileField(upload_to='documents/')),
                ('filename', models.CharField(editable=False, max_length=255)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document archivé',
                'verbose_name_plural': 'Documents archivés',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cooperative', 'is_active'], name='documents_arch_coop_idx')],
                'constraints': [models.UniqueConstraint(fields=('cooperative', 'doc_type', 'source_id'), name='unique_archive_per_source_and_type')],
            },
        ),
    ]
