# Generated by Django 5.1.4 on 2026-08-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentarchive',
            name='documents_arch_coop_idx',
        ),
        migrations.RemoveIndex(
            model_name='documenttemplate',
            name='documents_tmpl_coop_idx',
        ),
    ]
