# Generated by Django 5.1.4 on 2026-08-16 22:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_documentarchive_documents_arch_coop_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='documentarchive',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='documenttemplate',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
