# Generated by Django 5.1.4 on 2026-07-11 15:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('cooperatives', '0002_cooperative_address_cooperative_city_and_more'),
        ('partners', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmée'), ('partially_delivered', 'Partiellement livrée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='partners.partner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Entrepôt source des marchandises livrées.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Commande de vente',
                'verbose_name_plural': 'Commandes de vente',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_ordered', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_delivered', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='catalog.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ligne de commande de vente',
                'verbose_name_plural': 'Lignes de commande de vente',
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['cooperative', 'status'], name='sales_sales_coopera_597585_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('cooperative', 'order_number'), name='unique_sales_order_number_per_cooperative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gt', 0)), name='sales_line_quantity_ordered_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delivered__gte', 0), ('quantity_delivered__lte', models.F('quantity_ordered'))), name='sales_line_delivered_within_ordered'),
        ),
    ]
