# Generated by Django 5.1.4 on 2026-08-16 22:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='salesorder',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='salesorderline',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
